#!/bin/sh
set -e

exec openvpn --dev $OPENVPN_SERVER_DEV \
	--dh /etc/ssl/openvpn-server/dh.pem \
	--ca /etc/ssl/openvpn-server/ca.pem \
	--cert /etc/ssl/openvpn-server/cert.pem \
	--key /etc/ssl/openvpn-server/key.pem \
	--mode server --tls-server \
	--topology "subnet" --push "topology subnet" \
	--ifconfig $OPENVPN_SERVER_IP $OPENVPN_SERVER_NETMASK \
	--push "route-gateway $OPENVPN_SERVER_IP" \
	--client-config-dir /vpn/ccd-dir -ccd-exclusive \
	--proto tcp --port 1194 --comp-lzo adaptive \
	--persist-tun --persist-key --client-to-client --up-delay --keepalive 10 120