#!/bin/sh
set -e

exec openvpn --dev $OPENVPN_SERVER_DEV \
	--dh /etc/ssl/openvpn-server/dh.pem \
	--ca /etc/ssl/openvpn-server/ca.pem \
	--cert /etc/ssl/openvpn-server/cert.pem \
	--key /etc/ssl/openvpn-server/key.pem \
	--tls-server \
	--server $OPENVPN_SERVER_NETWORK $OPENVPN_SERVER_NETMASK \
	--topology subnet \
	--proto tcp --port 1194 --comp-lzo adaptive \
	--ifconfig-pool-persist ipp.txt --persist-tun \
	--persist-key --client-to-client --up-delay --keepalive 10 120